name: Alert about super-submodule reference differences
description: |
  This action shows incoming and outgoing commit logs between the commit recorded in the superproject [in SUPER-COMMIT] for each submodule and that submodule's master branch [or SUB-BRANCH].
inputs:
  message:
    description: >
      Print MESSAGE before the first commit log (only if there are such).
    required: false
    default: >
      Found pending submodule changes to be incorporated into the superproject:
  super-base:
    description: >
      Use submodules as recorded in SUPER-COMMIT (instead of what is currently checked out).
    required: false
  submodule-base:
    description: >
      Compare the recorded submodule reference with SUB-BRANCH in each submodule (default: master).
    required: false
  fail-on-differences:
    description: >
      Boolean flag whether to fail the action if there are any differences between the superproject and submodule references.
    required: false
    default: false
outputs:
  differences-found:
    description: >
      Whether there are any differences between the superproject and submodule references; "true" or "false".
    value: ${{ steps.check.outputs.differences-found }}
  logs:
    description: >
      Plain text log of the incoming / outgoing commits, if there are any.
    value: ${{ steps.check.outputs.logs }}
  markdown-logs:
    description: >
      Markdown-formatted log of the incoming / outgoing commits, if there are any.
    value: ${{ steps.check.outputs.markdown-logs }}
runs:
  using: composite
  steps:
    - name: Checkout git-extensions
      uses: actions/checkout@v4
      with:
        repository: inkarkat/git-extensions
        path: git-extensions
    - name: Checkout shell-converters
      uses: actions/checkout@v4
      with:
        repository: inkarkat/shell-converters
        path: shell-converters
    - name: Checkout shell-filters
      uses: actions/checkout@v4
      with:
        repository: inkarkat/shell-filters
        path: shell-filters
    - name: Checkout shell-filter-effect
      uses: actions/checkout@v4
      with:
        repository: inkarkat/shell-filter-effect
        path: shell-filter-effect
    - name: Checkout headers
      uses: actions/checkout@v4
      with:
        repository: inkarkat/headers
        path: headers
    - name: Checkout executionMarker
      uses: actions/checkout@v4
      with:
        repository: inkarkat/executionMarker
        path: executionMarker
    - name: Checkout miniDB
      uses: actions/checkout@v4
      with:
        repository: inkarkat/miniDB
        path: miniDB
    - name: Checkout shell-scripting
      uses: actions/checkout@v4
      with:
        repository: inkarkat/shell-scripting
        path: shell-scripting
    - id: check
      env:
        MESSAGE: ${{ inputs.message }}
        SUPER_BASE: ${{ inputs.super-base }}
        SUBMODULE_BASE: ${{ inputs.submodule-base }}
        FAIL_ON_DIFFERENCES: ${{ inputs.fail-on-differences }}
        OUTPUT_DIFFERENCES_FOUND: differences-found
        OUTPUT_LOGS: logs
        OUTPUT_MARKDOWN_LOGS: markdown-logs
      run: |
        git config --global --add include.path "${GITHUB_WORKSPACE}/git-extensions/gitconfig"
        for dependencyProject in git-extensions shell-converters shell-filters shell-filter-effect headers executionMarker miniDB shell-scripting
        do
          PATH="${GITHUB_WORKSPACE}/${dependencyProject}/bin:${PATH}"
        done

        "${GITHUB_ACTION_PATH}/check.sh"
      shell: bash
