name: Alert about super-submodule reference differences
description: |
  This action shows incoming and outgoing commit logs between the commit recorded in the superproject [in SUPER-COMMIT] for each submodule and that submodule's master branch [or SUB-BRANCH].
inputs:
  message:
    description: >
      Print MESSAGE before the first commit log (only if there are such).
    required: false
    default: >
      Found pending submodule changes to be incorporated into the superproject:
  super-base:
    description: >
      Use submodules as recorded in SUPER-COMMIT (instead of what is currently checked out).
    required: false
  submodule-base:
    description: >
      Compare the recorded submodule reference with SUB-BRANCH in each submodule (default: master).
    required: false
  fail-on-differences:
    description: >
      Boolean flag whether to fail the action if there are any differences between the superproject and submodule references.
    required: false
    default: false
outputs:
  differences-found:
    description: >
      Whether there are any differences between the superproject and submodule references; "true" or "false".
    value: ${{ steps.check.outputs.differences-found }}
  logs:
    description: >
      Log of the incoming / outgoing commits, if there are any.
    value: ${{ steps.check.outputs.logs }}
runs:
  using: composite
  steps:
    - name: Checkout git-extensions
      uses: actions/checkout@v4
      with:
        repository: inkarkat/git-extensions
        path: git-extensions
    - id: check
      env:
        MESSAGE: ${{ inputs.message }}
        SUPER_BASE: ${{ inputs.super-base }}
        SUBMODULE_BASE: ${{ inputs.submodule-base }}
        FAIL_ON_DIFFERENCES: ${{ inputs.fail-on-differences }}
      run: |
        git config --global --add include.path "${GITHUB_WORKSPACE}/git-extensions/gitconfig"
        PATH="${GITHUB_WORKSPACE}/git-extensions/bin:${PATH}"

        typeset -ar statusToBoolean=(true false)
        case "$FAIL_ON_DIFFERENCES" in
          true)   typeset -ar statusToAnnotation=(error notice error)
                  typeset -ar statusToFinalStatus=(1 0)
                  ;;
          false)  typeset -ar statusToAnnotation=(warning notice error)
                  typeset -ar statusToFinalStatus=(0 0)
                  ;;
          *)      printf >&2 'ERROR: Invalid fail-on-differences: %s\n' "$FAIL_ON_DIFFERENCES"; exit 2;;
        esac
        typeset -ar statusToMessage=('Differences found between superproject and submodule(s)' 'No differences found between superproject and submodule(s)' 'An unexpected error occurred')

        status=0; logs="$(git-supersubinout ${MESSAGE:+--message "$MESSAGE"} ${SUPER_BASE:+--super-base "$SUPER_BASE"} ${SUBMODULE_BASE:+--submodule-base "$SUBMODULE_BASE"})" || status=$?

        printf 'differences-found=%s\nlogs<<EOF\n%s\nEOF\n' "${statusToBoolean[$status]:-false}" "$logs" >> "$GITHUB_OUTPUT"
        printf '::%s::%s\n' "${statusToAnnotation[$status]:-error}" "${statusToMessage[$status]:-${statusToMessage[2]}}"
        exit "${statusToFinalStatus[$status]:$status}"
      shell: bash
